version: '3'
services:
  app:
    build:
      context: .
    container_name: railsapp
    environment:
      - RAILS_ENV=development
      - SPROCKETS_CACHE=/cache
    volumes:
      - .:/webapp
      - cache:/cache
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  mysql:
    image: mysql:5.6
    container_name: mysql
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql_data:
  cache: